import './styles.css';
import {addStreams,addStream} from './streams'

addStreams([
  ['once','a single value',`Obs.just(42)`],
  ['several','several values',`Obs.from([1,2,3])`],
  ['spaced','several values with delay',`Obs.for([1,2,3],x=>Obs.just(x).delay(500))`],
  ['seeded','several values with delay and seed',`Obs.for(['a','b','c'],x=>Obs.just(x).delay(500)).startWith('Alphabet!')`],
  ['secs','seconds elapsed',`Obs.interval(1000)`],
  ['source','the source code :)',
   `Obs.for(docsource.match(/\\w+/g),x=>Obs.just(x).delay(800)).repeat()`],
  ['tick','metronome',`streams.secs.map( s=> s%2 ? 'tock' : 'tick' )`],
  ['filter','only containing "i"',
  `streams.tick.merge(streams.source).filter(i=>i.match(/i/))`],
  ['click','<button id="clickbtn">Click me quickly!</button>',
   `fromClick('#clickbtn').map(()=>'click')`],
  ['speed','# consecutive button clicks?',
   `streams.click.buffer(()=>streams.click.debounce(250)).map(l=>l.length)`],
  ['total','# of clicks in total?',
   `streams.speed.scan((acc,latest)=>acc+latest)`],
  ['field','<input id="field" placeholder="say something"></input>',
   `fromEvent('#field','input').map(e=>e.target.value)`],
  ['enter','enter key in the field',
   `fromEvent('#field','keyup').filter(e=>e.keyCode === 13).map(e=>'Enter!')`],
  ['throttlestart','with less spam:',`streams.field.debounce(1000)`],
  ['throttleend','same, but from "behind":',`streams.field.sample(1000)`],
  ['throttlepure','trying throttle too:',`streams.field.throttle(1000)`],
  ['save','<button id="savebtn">Save</button>',
   `streams.field.sample(fromClick('#savebtn'))`],
  ['over','<div id="bluesquare">hover over me!</div>',
   `fromEvent('#bluesquare','mouseover').map(e=>'Hello!')`],
  ['out','and saying goodbye',
   `fromEvent('#bluesquare','mouseout').map(e=>'Ack, dont leave!')`],
  ['url','<button id="fetchbtn">fetch random user</button>',
   `fromClick('#fetchbtn').map(e=>USER_URL+Math.ceil(Math.random()*10)).share()`],
  ['response','getting data back',
   `streams.url.flatMap(url=>Obs.fromPromise(getJSON(url))).map(o=>o.name)`],
  ['ping','<button id="triggerping">Trigger</button>',`proxy.delay(1000).merge(fromClick('#triggerping')).map(i=>'ping')`],
  ['pong','right back at ya!',`(()=>{ let pong = streams.ping.delay(1000).map(i=>'pong'); pong.subscribe(proxy); return pong; })()`],
  ['master','<button id="toggler">Toggle</button>',`fromClick('#toggler').startWith('getgoing').scan(acc=>!acc,true)`],
  ['boaty','being annoying',`streams.source.filter(i=>i.match(/^[a-z]*$/)).map(x=>x+'y mc'+x+'face').pausable(streams.master)`]
])
